title: MerchantPerson
description: A simple website for my personal projects and experiments.
theme: just-the-docs
color_scheme: dark # Color scheme supports "light" (default) and "dark" 

url: https://merchantperson.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
